services:
  web:
    build: containers/nginx
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    restart: always
    depends_on:
      - vault
    volumes:
      - vault-data:/vault/data
  db:
    build: containers/sqlite
    environment:
      -  USER_SQLITE=sqlite
      -  GROUP_SQLITE=sqlite
    volumes:
      - ./volumes/sqlite:/data
    restart: always
  backend:
    build: containers/fastify
    ports:
      - "3000:3000"
    volumes:
      - ./containers/fastify:/app
      - ./volumes/node_modules:/app/node_modules
      - ./volumes/sqlite:/data
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    depends_on:
      - vault

  vault:
    build: containers/vault
    container_name: ft_transcendence_vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
      - ./containers/vault/config:/vault/config

volumes:
  vault-data:
